### ISSUE TITLE
Event: type check on 'fromTime' and 'toTime'

### ISSUE THREAD

**Issue by cbolton97** [shannonjanehogan/google-calendar-dsl#11]
An Event's `fromTime` and 'toTime' must be in a format acceptable according to our grammar rules (see doc)

**Comment by jregchiu** [comment]
FYI I just changed the time formats a tiny bit to make the evaluation easier later (by requiring a colon separating hours from minutes). If anyone feels strongly about not having a colon though, totally fine without.
